---
title: "Introduction to KEGGerator"
author: "Tyler Bradley"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to KEGGerator}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  echo = TRUE,
  warning = FALSE,
  message = FALSE,
  comment = "#>"
)
```

This goal of this vignette is to walk you through the basic functionality of the `KEGGerator` package. This package is designed for use with data gerenated using the `dada2` package, in the form of a `phyloseq` object. For this walk-through, we will use the `GlobalPatterns` dataset from the `phyloseq` package. 

```{r load-libraries}
library(phyloseq)
library(KEGGerator)
library(tidyverse)
```

```{r}
patterns_file <- system.file("data", "GlobalPatterns.Rdata", package = "phyloseq")
load(patterns_file)

# Filter data for runtime effeciency - reduces dataset to ~10% of original size
patterns <- filter_taxa(GlobalPatterns, function(x)sum(x)>10000, prune = TRUE)
```



```{r}
patterns_tax <- tax_tibble(patterns)
patterns_genomes <- genomes_tibble(patterns)
```

First, 
